# Generated by Django 2.0.5 on 2018-05-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.IntegerField(default=0)),
                ('pay_period', models.DateTimeField(verbose_name='Paid Date')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
