# Generated by Django 2.0.5 on 2018-05-24 00:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payroll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='pay_period',
        ),
        migrations.AddField(
            model_name='payroll',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
