# Generated by Django 2.0.5 on 2018-05-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20180523_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.IntegerField(default=-1, primary_key=True, serialize=False)),
            ],
        ),
    ]
