# Generated by Django 2.0.5 on 2018-05-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_auto_20180524_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobgroup',
            name='id',
        ),
        migrations.AlterField(
            model_name='jobgroup',
            name='group',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
